# Generated by Django 3.0.3 on 2020-02-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='automobile.Person'),
        ),
    ]
